pipeline {
    agent any
    environment {
                PATH = "/opt/maven3/bin:$PATH"
   }
    stages {
        stage('Maven-Build1') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
}
